<?php

namespace Nkg\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProspectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
}
