<?php

namespace Nkg\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InterestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterestRepository extends EntityRepository {

	public function findInterests() {
		return $this->findBy(array("active"=>true),array("label"=>"ASC"));
	}
}
