<?php

namespace Nkg\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LocalisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalisationRepository extends EntityRepository {
  public function findLocalisation() {
		$qb = $this->getLocalisationQuery();
		$query = $qb->getQuery();
		return $query->getResult();
	}

	public function getLocalisationQuery() {
		$qb = $this->_em->createQueryBuilder();
		$qb->select(array('communes'))
				->from('NkgContactBundle:Localisation', 'communes')
				->innerJoin('communes.departement', 'departement')
				->where(
						$qb->expr()->andX(
								$qb->expr()->eq('communes.active', true),
								$qb->expr()->eq('departement.active', true)
						)
				)
//				->orderBy("communes.label", "ASC")
		;
		return $qb;
	}

	public function findLocalisationByCountryId($departement_id) {
		$qb = $this->_em->createQueryBuilder();
		$qb->select(array('communes'))
				->from('NkgContactBundle:Localisation', 'communes')
				->innerJoin('communes.departement', 'departement')
				->where(
						$qb->expr()->andX(
								$qb->expr()->eq('communes.active', true), $qb->expr()->eq('departement.active', true), $qb->expr()->eq('departement.id', ':id')
						)
				)
				->setParameter("id", $departement_id)
				->orderBy("communes.label", "ASC")
		;

		$query = $qb->getQuery();
		return $query->getResult();
	}
}
